Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -34,11 +34,23 @@ jobs:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
+    - name: Check current directory and list files
+      run: |
+        echo "Current directory:"
+        pwd
+        echo "List of files:"
+        ls -la
+
     - name: Update Kubernetes manifest with new image
       run: |
-        cd manifest/k8s 
-        ls -la  
-        sed -i "s|image:.*|image: $REPOSITORY_URI:$IMAGE_TAG|" deploy-basic.yml
+        if [ -d "manifest/k8s" ]; then
+          cd manifest/k8s 
+          ls -la  
+          sed -i "s|image:.*|image: $REPOSITORY_URI:$IMAGE_TAG|" deploy-basic.yml
+        else
+          echo "Error: manifest/k8s directory not found"
+          exit 1
+        fi
       env:
         AWS_REGION: ap-northeast-2
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
